apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-rzzl
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-rzzl
    app.kubernetes.io/part-of: ci10t-776-0074-app
  name: devfile-sample-rzzl
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-rzzl
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-rzzl
    spec:
      containers:
      - image: quay.io/pmacik-testing/ci10t-776-0074-tenant/ci10t-776-0074-app/devfile-sample-rzzl@sha256:90a147cef5c3bd2f02af365552aee6b5f2e95e4c84dcac147dd85d21704847ac
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
